Add parsec provisionsing example
veracruz-project/dpu pull request #1
Opened 2023-11-03 16:33 UTC by mohamed-arm

2023-11-07 13:13 UTC, gbryant-arm requested changes
Looks good, just requires minor code and doc refactoring

2023-11-07 13:13 UTC, gbryant-arm commented on host/examples/parsec_execute/Cargo.toml
> +description = "The test program for provisioning a responder and executing a remote workload."
Can you update the description to reflect what the program does?

2023-11-07 13:13 UTC, gbryant-arm commented on host/examples/parsec_execute/src/main.rs
> +//! An example to send a file.
Same as above

2023-11-07 13:13 UTC, gbryant-arm commented on host/examples/parsec_execute/src/main.rs
> +//    let data = b"bar".to_vec();
You can remove this now

2023-11-07 13:13 UTC, gbryant-arm commented on host/examples/parsec_execute/src/main.rs
> +fn get_file_as_byte_vec(filename: &String) -> Vec<u8> {
It is better practice to return an error than panicking. I recommend the use of anyhow errors (cf. main())

2023-11-07 13:13 UTC, gbryant-arm commented on host/examples/parsec_execute/src/main.rs
> +    info!("Preparing provisions...");
What are you provisioning?

2023-11-07 13:13 UTC, gbryant-arm commented on host/examples/parsec_execute/src/main.rs
> +    info!("Provisioning DPU...");
What are you provisioning?

2023-11-07 13:13 UTC, gbryant-arm commented on host/examples/parsec_execute/src/main.rs
> +    info!("Requesting remote execution...");
Can you make the info! more descriptive by mentioning what you are executing?

2023-11-07 13:13 UTC, gbryant-arm commented on host/examples/parsec_execute/src/main.rs
> +    info!("Requesting remote execution #2");
Same here

2023-11-08 16:01 UTC, gbryant-arm commented on host/examples/parsec_execute/src/main.rs
> +const PARSEC_APP_NAME: &str = "parsec_app";
This its the parsec client's binary, right? Your model makes it difficult to understand and reproduce what code is actually provisioned and executed on the remote target.
How about you push the parsec-tool's binary instead and execute it over the CLI? Should solve most of your problems

2024-01-09 16:57 UTC, gbryant-arm commented on host/examples/parsec_execute/src/main.rs
> +    info!("Requesting p");
"Requesting parsec execution"?

2024-01-09 22:18 UTC, mohamed-arm commented
Addressed the comments.

2024-01-15 19:30 UTC, gbryant-arm approved these changes
LGTM

2024-01-17 16:06 UTC, merged