Add deploy script for parsec_tool example
veracruz-project/dpu pull request #3
Opened 2024-01-03 01:02 UTC by mohamed-arm

2024-02-07 17:06 UTC, gbryant-arm approved these changes

2024-02-07 20:22 UTC, gbryant-arm requested changes
Looks like setup_env.sh and script.sh are doing the same thing?

2024-02-07 20:28 UTC, mohamed-arm commented
> Looks like setup_env.sh and script.sh are doing the same thing?

Fixed. Removed script.sh and updated the Readme.

2024-02-08 11:35 UTC, gbryant-arm approved these changes

2024-02-08 11:36 UTC, merged